### ISSUE TITLE
执行docker-compose up -d报如下错误

### ISSUE THREAD

**Issue by xiexiaoxin01** [glzjin/CTFd-Whale#18]
执行docker-compose up -d报如下错误，请问要如何解决？

ERROR: unsatisfiable constraints:
python (missing):
required by: world[python]
python-dev (missing):
required by: world[python-dev]
ERROR: Service ‘ctfd’ failed to build: The command ‘/bin/sh -c sed -i ‘s/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g’ /etc/apk/repositories && apk update && apk add python python-dev linux-headers libffi-dev gcc make musl-dev py-pip mysql-client git openssl-dev’ returned a non-zero code: 2

**Comment by mlzxgzy** [comment]
你可以试试把docker-compose.yml里的ctf里的build标签从
build: .
改成
build:
  context: .
  network: host
如果报错就把最上面的version改成3试试

**Comment by Err0rCM** [comment]
请将Dockerfile中第一个RUN中python和python-dev改成python2或python3，python2-dev或python3-dev即可解决问题

**Comment by glzjin** [comment]
此分支已不再维护，如需继续使用请参考 https://github.com/frankli0324/ctfd-whale 。
