### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by saltfish233** [glzjin/CTFd-Whale#21]
![image](https://user-images.githubusercontent.com/50053654/171561727-45520344-0700-4b4b-b2f8-d6fa9017e316.png)

我在使用时遇到了unicode编码错误，但是修改日志显示是frp_utils.py中的put方法传入了\u200b，我尝试使用quote但是没能成功解决。

**Comment by saltfish233** [comment]
容器可以创建但创建好后进入报ERR_CONNECTION_REFUSED错误

**Comment by kIl3rr** [comment]
在部署题目后，frp端口映射有问题，也看到了这个报错 @saltfish233  解决了吗

**Comment by glzjin** [comment]
此分支已不再维护，如需继续使用请参考 https://github.com/frankli0324/ctfd-whale 。
