### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by djerryz** [glzjin/CTFd-Whale#3]
1. 定时回收容器的机制, 即设定每道题的答题时间范围
2. 增加题目是否可以复用的属性, 若否, 则该题每次创建时, 为每个用户启用单独的容器实例
   2.1 针对非复用容器, 希望能控制容器实例个数, 当到达限制, 前端提示进入排队等候
3. 用户分离
   3.1 WEB可以通过hash的子域名+Nginx host绑定实现每个用户单独的域名访问
   3.2 针对nc连接类型的题目,能做tcp层的认证, 即有前置的服务器A, nc连接到A, 输入口令后, A会透明代理到口令对应的题目.(目前golang已实现)
  (3.3 下发vgrant 虚拟题目, 前端返回VPN接入口令)
4. 底层Paas四个组件模块:
   
![ctf_paas](https://user-images.githubusercontent.com/24947060/68564776-726e8680-048c-11ea-9d1f-a3b197f95463.png)

上面,仅为我的想法,Thanks!

**Comment by glzjin** [comment]
感谢您的建议哈~

1、之后可能会有。在题目里加个字段。
2、同上，目前的建议是手工管理，和以前的普通题目一样上题。我自己的平台为了统一就没考虑这些了。
3、目前的功效和你提到的3.1相同。3.2 的话，可以做，但直接映射映射出来能满足需求我也没多大动力改了。vgrant 之类的全虚拟化实例，可能以后会有吧。

**Comment by djerrystyle** [comment]
了解.

推荐一下资源, 看能不能用上:
1. https://captainduckduck.com/ == 组件Nginx+docker
2. 前置的golang认证相关代码(把log后缀改成rar解压): 
[tcpproxy.log](https://github.com/glzjin/CTFd-Whale/files/3834003/tcpproxy.log)

**Comment by 0akarma** [comment]
个人觉得Issue主的建议是后续整个（大）CTF平台（自动）容器化的一种思路～
但是在当下，我觉得配合frps和swarm已经能与某些商业化ctf平台媲美，这对和owner一样维（重复）护（劳动）着自己平台的人来说，已经能减清自己很多负担。

后续，我也会把前些时间研究的一个基于docker-compose的plugin和适配awd的plugin开源，希望后面能跟owner交流交流～

**Comment by glzjin** [comment]
@0akarma 欢迎欢迎~我的 QQ: 3054879403

**Comment by djerrystyle** [comment]
请问一下docker-compose后期会支持吗.
如果只是填写image字段,有些启动的命令没法传入

**Comment by glzjin** [comment]
@djerrystyle 并不会支持，docker-compose 只是调用了 docker 的api，其自身并没有提供对外的api。

如要在镜像启动时传入环境变量等参数，建议自己写个 Dockerfile 继承实现。

如要组内网，可参考更新说明，写一个 json 在镜像那即可启动多个容器并自动组成内网。

**Comment by glzjin** [comment]
此分支已不再维护，如需继续使用请参考 https://github.com/frankli0324/ctfd-whale 。
