### ISSUE TITLE
jQuery missing

### ISSUE THREAD

**Issue by frankli0324** [glzjin/CTFd-Whale#7]
新版CTFd(2.2.0)的base.html中延迟引入jQuery，需要在config.html中重新引入，或者放到新的文件中延迟引入

https://github.com/CTFd/CTFd/blob/354954bbe90cf583f05d272b9ce0437c1c9ad24f/CTFd/themes/core/templates/base.html#L193

**Comment by glzjin** [comment]
Ok，可以麻烦发个pr吗，谢谢🙏


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：Frank <notifications@github.com>
日期：2020-02-14 18:02:19
收件人：glzjin/CTFd-Whale <CTFd-Whale@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[glzjin/CTFd-Whale] jQuery missing (#7)
新版CTFd(2.2.0)的base.html中延迟引入jQuery，需要在config.html中重新引入，或者放到新的文件中延迟引入
https://github.com/CTFd/CTFd/blob/354954bbe90cf583f05d272b9ce0437c1c9ad24f/CTFd/themes/core/templates/base.html#L193

**Comment by frankli0324** [comment]
我吃完饭emm

**Comment by glzjin** [comment]
谢谢～


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：Frank <notifications@github.com>
日期：2020-02-14 18:07:31
收件人：glzjin/CTFd-Whale <CTFd-Whale@noreply.github.com>
抄送：glzjin <glzjin@zhaojin97.cn>, Comment <comment@noreply.github.com>
主题：Re: [glzjin/CTFd-Whale] jQuery missing (#7)
我吃完饭emm

**Comment by glzjin** [comment]
https://github.com/glzjin/CTFd-Whale/pull/8 谢谢
